/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChipInput: typeof import('./src/components/ChipInput.vue')['default']
    CommandStatusModal: typeof import('./src/components/CommandStatusModal.vue')['default']
    DriverEditor: typeof import('./src/components/DriverEditor.vue')['default']
    DriverFormComponent: typeof import('./src/components/DriverFormComponent.vue')['default']
    DriverInspectModal: typeof import('./src/components/DriverInspectModal.vue')['default']
    DriverSelector: typeof import('./src/components/DriverSelector.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    MatchRuleFormComponent: typeof import('./src/components/MatchRuleFormComponent.vue')['default']
    MatchRuleInputModal: typeof import('./src/components/MatchRuleInputModal.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ProgressModal: typeof import('./src/components/ProgressModal.vue')['default']
    ProgressStepper: typeof import('./src/components/ProgressStepper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaggedInput: typeof import('./src/components/TaggedInput.vue')['default']
    TaskStatus: typeof import('./src/components/TaskStatus.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UnsaveConfirmModal: typeof import('./src/components/UnsaveConfirmModal.vue')['default']
    UpdateModal: typeof import('./src/components/UpdateModal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
