// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CPUTemperature() {
  return window['go']['sysinfo']['SysInfo']['CPUTemperature']();
}

export function OSInfo() {
  return window['go']['sysinfo']['SysInfo']['OSInfo']();
}

export function ResolvedHardware() {
  return window['go']['sysinfo']['SysInfo']['ResolvedHardware']();
}
