// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysinfo} from '../models';

export function CPUTemperature():Promise<number>;

export function OSInfo():Promise<sysinfo.OSInfo>;

export function ResolvedHardware():Promise<sysinfo.ResolvedHardware>;
