// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['update']['Updater']['CheckForUpdates'](arg1);
}

export function TriggerNativeUpdate(arg1, arg2) {
  return window['go']['update']['Updater']['TriggerNativeUpdate'](arg1, arg2);
}
