// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';

export function CheckForUpdates(arg1:boolean):Promise<update.UpdateCheckResult>;

export function TriggerNativeUpdate(arg1:string,arg2:boolean):Promise<void>;
