name: Create Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: markmybytes/install-it/.github/workflows/test.yml@main

  build:
    needs: test
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: ["386", amd64]
        include:
          - goarch: "386"
            build-name: windows-x86
            wv2arch: x86
          - goarch: amd64
            build-name: windows-x64
            wv2arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go environment
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install Wails CLI
        run: |
          $WAILS_VERSION = go list -m -f '{{.Version}}' github.com/wailsapp/wails/v2
          go install github.com/wailsapp/wails/v2/cmd/wails@$WAILS_VERSION

      - name: Set up Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: 'frontend/package.json'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'


      - name: Install NPM dependencies
        run: |
          cd frontend
          npm ci

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      - name: Build binary for Windows (${{ matrix.goarch }})
        run: |
          set GOARCH=${{ matrix.goarch }}
          wails build -upx -ldflags "-X main.buildVersion=${{ github.ref_name }}"

      - name: Download and extract WebView2 runtime
        run: |
          cd build\bin
          curl -o webview2.cab -L https://github.com/westinyang/WebView2RuntimeArchive/releases/download/132.0.2957.140/Microsoft.WebView2.FixedVersionRuntime.132.0.2957.140.${{ matrix.wv2arch }}.cab
          mkdir internals\bin
          expand -r webview2.cab -F:* internals\bin
          move internals\bin\Microsoft.WebView2.FixedVersionRuntime.* internals\bin\WebView2

      - name: Download PCI ID database
        run: |
          cd build\bin
          mkdir internals\data
          curl -sL -o internals\data\pci.ids.gz https://pci-ids.ucw.cz/v2.2/pci.ids.gz

      - name: Bundle binary and WebView2 files into ZIP
        run: |
          cd build\bin
          7z a install-it.${{ matrix.build-name }}.zip install-it.exe internals\data -mx8
          7z a install-it.${{ matrix.build-name }}-bundled.zip install-it.exe internals -mx8

      - name: Collect artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.goarch }}
          path: build/bin/*.zip

  build-updater:
    needs: test
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
        include:
          - architecture: x86
            build-name: windows-x86
          - architecture: x64
            build-name: windows-x64

    steps:
      - name: Checkout updater repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/install-it-updater

      - name: Setup Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          architecture: ${{ matrix.architecture }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      - name: Build the executable
        run: |
          pyinstaller .\src\main.py -cDF -n updater.${{ matrix.build-name }} -i .\icon.ico

      - name: Upload updater artifact
        uses: actions/upload-artifact@v7
        with:
          name: updater-${{ matrix.architecture }}
          path: dist/updater.${{ matrix.build-name }}.exe

  release:
    needs: [build, build-updater]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true

      - name: Create release with artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
